### ISSUE TITLE
Greeting and starting the reviewing process

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#1]
Hi Viktor,
Nice to e-meet you 👋 and thanks for your effort on this submission. My name is Trung - an Android developer at Nimble and I'd like to conduct the feedbacks via Issues ticket regarding your performance here. 
Keep in mind, this is a bidirectional process, so we'd love to hear back from you as well, so please don't hesitate to raise your question/correction in case we missed anything.
If we're aligned on any issue here and you'd like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up those fixes 😇

The first issue I noticed is that the process you're pushing your code didn't comply with our requirement (via pull request, branching per push). It might not mean anything to judge on your technical/coding skill, but we'd like to see clearly if you're familiar with such process prior to joining us.

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee Trung,
It's a pleasure to meet you as well and thank you very much for taking your time for the feedback.
I found your raised issues extremely helpful and I will revise them accordingly.

**Comment by sleepylee** [comment]
Hi @ViktorArtemiev, happy Monday 😇. 
Upon your revise and update, kindly help us closing the Issue that had been addressed and fixed by your works, by that way, we will know when to start our second round of reviewing the code (or you can inform us as well).

Good luck and happy coding 🤘
