### ISSUE TITLE
Feature request: please unlock the rotation

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#10]
We'd love to see how well the app can handle the system change, persistence, stability etc..

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee Trung

Hmm, the rotation has not been locked at all.
Could it be a problem with your device settings?

This video demonstrates the rotation functionality
https://drive.google.com/open?id=1MpykLm8wn_kLJDgR3kR-CP6M0HRffA5f

**Comment by sleepylee** [comment]
hi @ViktorArtemiev, thanks for your reply, we will recheck this accordingly
