### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#2]
while playing with the app, we noticed a crash occurs. Would be great if you could address and patch it.
![image](https://user-images.githubusercontent.com/13435717/62184887-3eae9b80-b38a-11e9-9883-a4047bda1e2b.png)

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee Trung

The issue has been fixed.
Pull-request linked #11
