### ISSUE TITLE
Requesting for more testing coverage

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#3]
We'd like to see further testing coverage from your side, given that testing is never enough nor a guarantee to a quality application, but we still prefer to see how further can you push with your current architecture, that leveraging Dagger, ViewModel...etc..

**Comment by nhphong** [comment]
@ViktorArtemiev Any update on this issue?
How about an instrumented test with Espresso and Dagger being set up (to inject mock object)?

**Comment by ViktorArtemiev** [comment]
Hello @nhphong 
[MainViewModel](https://github.com/ViktorArtemiev/Surveys/blob/master/app/src/main/java/co/nimblehq/screen/main/MainViewModel.kt) has been already covered by Unit tests. 
You can check it out in this commit https://github.com/ViktorArtemiev/Surveys/pull/19/commits/78756d47731df260e3260aabeed2199334c30914

The next step will be to write the instrumented test for [MainActivity](https://github.com/ViktorArtemiev/Surveys/blob/master/app/src/main/java/co/nimblehq/screen/main/MainActivity.kt) leveraging Espresso and Dagger. The task is expected to be completed by tomorrow.

**Comment by ViktorArtemiev** [comment]
Hi @nhphong 
[MainActivity](https://github.com/ViktorArtemiev/Surveys/blob/master/app/src/main/java/co/nimblehq/screen/main/MainActivity.kt) has been covered by instrumentation tests.
Tests can be checked out in this commit f70e122ed6c995d0ec70396b5c37ed8c808c5630

PR linked #19
