### ISSUE TITLE
Few minor suggestion for more kotlin flavor

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#5]
- Scoping functions like `.run()` or `.apply()`...can be used for these [cases](https://github.com/ViktorArtemiev/Surveys/blob/430aacf42c66f1abe8ad6a281a5b589c466e8227/app/src/main/java/co/nimblehq/screen/main/MainActivity.kt#L59) where you can improve the readability of the codes.
- `this@MainActivity` is a bit redundant imo, since the scope is not overlapped anywhere it calls, but I'm kind of understand your clarity preference 😇

**Comment by sleepylee** [comment]
Also,
- If we just need a similar form of `publish static final String` like the good old java style, instead of creating a companion object just to hold such things like [here](https://github.com/ViktorArtemiev/Surveys/blob/430aacf42c66f1abe8ad6a281a5b589c466e8227/app/src/main/java/co/nimblehq/SurveysAccount.kt#L19), how about keeping them as const on the top class level?

**Comment by ViktorArtemiev** [comment]
Hello @sleepylee Trung

Code readability improved.

Pull-request linked #13
