### ISSUE TITLE
SurveyAccount seems to be a bit problematic in its design

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#6]
- This [SurveyAccount](https://github.com/ViktorArtemiev/Surveys/blob/master/app/src/main/java/co/nimblehq/SurveysAccount.kt) class is holding a connection directly to SharePreference, managing the i/o flow, which is not so ideal in case we'd like to change from SharePreference to a different kind of storage. Basically, an abstract layer in between fetching the data from local storage and the account management itself could be more flexible if we want to change the system later.
- The class itself is currently placed at the same level as the Application class, shouldn't it be organized in a sub-directory?

**Comment by ViktorArtemiev** [comment]
Hi @sleepylee Trung

> This SurveyAccount class is holding a connection directly to SharePreference, managing the i/o flow, which is not so ideal in case we'd like to change from SharePreference to a different kind of storage. Basically, an abstract layer in between fetching the data from local storage and the account management itself could be more flexible if we want to change the system later.

Agree, good point.
The functionality redesigned.

> The class itself is currently placed at the same level as the Application class, shouldn't it be organized in a sub-directory?

The class moved to sub-directory.
Thanks!

Pull-request linked #14
