### ISSUE TITLE
Activity (View) is still holding a bit many logics to its side.

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#7]
I saw from [here](https://github.com/ViktorArtemiev/Surveys/blob/430aacf42c66f1abe8ad6a281a5b589c466e8227/app/src/main/java/co/nimblehq/screen/main/MainActivity.kt#L69) that the View is holding a piece of UI changes where it doesn't know when the next state occurs `isVisible = true`. It might sound a bit nitpicking, but when `refresh()` shouldn't the ViewModel emit the loading state (similar) and let the View know as an observer as well? At least for the consistency in your idea of how we handle the loading state.

**Comment by ViktorArtemiev** [comment]
Hello @sleepylee Trung

You are right
it's better to handle this loading state via the observer in this case
Thank you! 

pull-request linked #15
