### ISSUE TITLE
Load image extension issue

### ISSUE THREAD

**Issue by sleepylee** [ViktorArtemiev/Surveys#8]
The issue is that it won't be applicable for any other image url that doesn't contain the `l` suffix. My recommendation is that instead of letting an extension function choose what should it display, we should pass to it what it should display only, in this case, the high quality url with the "l" appending can be defined as a backing field of the main model, how do you think?

**Comment by ViktorArtemiev** [comment]
Hello @sleepylee Trung

Totally agree with your point
this is not a good idea to hardcode the suffix.
Didn't consider that functionality might be applicable to any kind of URLs.

Thank you!

pull-request linked #16
